FROM ubuntu

RUN apt-get update
RUN apt-get install -y build-essential
RUN apt-get install -y g++
RUN apt-get install -y python-dev
RUN apt-get install -y bash-completion
RUN apt-get install -y supervisor
RUN apt-get install -y vim
RUN apt-get install -y openssh-server 
RUN mkdir /var/run/sshd

RUN cat /etc/skel/.bashrc >> ~/.bashrc
